produits:
    pattern:  /
    defaults: { _controller: EcommerceBundle:Produits:produits }
    
presentation:
    pattern:  /produit/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation }

test:
    pattern:  /test
    defaults: { _controller: EcommerceBundle:Test:ajout }
    
ecom_categories:
    pattern:  /categoiries
    defaults: { _controller: EcommerceBundle:Categories:menu }
    
categorieProduits:
    pattern:  /categories/{categorie}
    defaults: { _controller: EcommerceBundle:Produits:produits }
    
rechercheProduits:
    pattern:  /recherche
    defaults: { _controller: EcommerceBundle:Produits:rechercheTraitement }
    