<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
    
    // creation d'un query builder  de recherche de categorie dans le repository
    
    public function byCategorie($categorie)
    {
    $qb = $this->createQueryBuilder('u')
               ->select('u')
               ->where ('u.categorie = :categorie')
               ->andWhere('u.disponible = 1')
               ->orderBy('u.id')
               ->setParameter('categorie', $categorie);
               
               return $qb->getQuery()->getResult();
    
    }
    
    // creation d'un query builder de recheche d'un produit
    
    public function recherche($chaine)
    {
        // création d'un objet
        
        
        $qb = $this->createQueryBuilder('u')
                   ->select('u')
                   ->where('u.nom like :chaine')
                   ->andWhere('u.disponible = 1')
                   ->orderBy('u.id ')
                   ->setParameter('chaine', $chaine);
                   
        return $qb->getQuery()->getResult();
        
        
    }
    
    // creation d'un query builder pour les objects du panier
    
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
                  ->select('u')
                  ->where('u.id IN  (:array) ')
                  ->orderBy('u.id')
                  ->SetParameter('array', $array);
        
        return $qb->getQuery()->getResult();
        
        
    }
}
